// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package server.services.bookingService;

public interface AppointmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingService.Appointment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string patientId = 2;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string doctorId = 3;</code>
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctorId = 3;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();

  /**
   * <code>string dateTime = 4;</code>
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();
}
