// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package server.services.bookingService;

public interface CancelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingService.CancelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
