// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package server.services.bookingService;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingService.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientId = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string doctorId = 2;</code>
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctorId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();

  /**
   * <code>string dateTime = 3;</code>
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();
}
