// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package server.services.bookingService;

public interface ShiftListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingService.ShiftListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorId = 1;</code>
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctorId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();
}
