// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prescriptions.proto

package server.services.prescriptionsService;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prescriptionsService.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientId = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string doctorId = 2;</code>
   */
  java.lang.String getDoctorId();
  /**
   * <code>string doctorId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIdBytes();

  /**
   * <code>string expiryDate = 3;</code>
   */
  java.lang.String getExpiryDate();
  /**
   * <code>string expiryDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getExpiryDateBytes();
}
