// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prescriptions.proto

package server.services.prescriptionsService;

public interface DrugOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prescriptionsService.Drug)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string prescriptionsId = 2;</code>
   */
  java.lang.String getPrescriptionsId();
  /**
   * <code>string prescriptionsId = 2;</code>
   */
  com.google.protobuf.ByteString
      getPrescriptionsIdBytes();

  /**
   * <code>string drug = 3;</code>
   */
  java.lang.String getDrug();
  /**
   * <code>string drug = 3;</code>
   */
  com.google.protobuf.ByteString
      getDrugBytes();

  /**
   * <code>string doses = 4;</code>
   */
  java.lang.String getDoses();
  /**
   * <code>string doses = 4;</code>
   */
  com.google.protobuf.ByteString
      getDosesBytes();

  /**
   * <code>string comment = 5;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 5;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();
}
