// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prescriptions.proto

package server.services.prescriptionsService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prescriptionsService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
