// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prescriptions.proto

package server.services.prescriptionsService;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prescriptionsService.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errorMessage = 1;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
