// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prescriptions.proto

package server.services.prescriptionsService;

public final class PrescriptionsServiceImpl {
  private PrescriptionsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prescriptionsService_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prescriptionsService_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prescriptionsService_Prescription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prescriptionsService_Prescription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prescriptionsService_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prescriptionsService_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prescriptionsService_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prescriptionsService_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023prescriptions.proto\022\024prescriptionsServ" +
      "ice\"`\n\rCreateRequest\022\021\n\tpatientId\030\001 \001(\t\022" +
      "\020\n\010doctorId\030\002 \001(\t\"*\n\005drugs\022\010\n\004drug\020\000\022\t\n\005" +
      "doses\020\001\022\014\n\010comments\020\002\"n\n\014Prescription\022\n\n" +
      "\002id\030\001 \001(\t\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName" +
      "\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022" +
      "\014\n\004role\030\006 \001(\t\"%\n\rErrorResponse\022\024\n\014errorM" +
      "essage\030\001 \001(\t\"\007\n\005Empty2\263\001\n\rPrescriptions\022" +
      "S\n\006Create\022#.prescriptionsService.CreateR" +
      "equest\032\".prescriptionsService.Prescripti" +
      "on\"\000\022M\n\006GetAll\022\033.prescriptionsService.Em" +
      "pty\032\".prescriptionsService.Prescription\"" +
      "\0000\001BB\n$server.services.prescriptionsServ" +
      "iceB\030PrescriptionsServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_prescriptionsService_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prescriptionsService_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prescriptionsService_CreateRequest_descriptor,
        new java.lang.String[] { "PatientId", "DoctorId", });
    internal_static_prescriptionsService_Prescription_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_prescriptionsService_Prescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prescriptionsService_Prescription_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Password", "Role", });
    internal_static_prescriptionsService_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_prescriptionsService_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prescriptionsService_ErrorResponse_descriptor,
        new java.lang.String[] { "ErrorMessage", });
    internal_static_prescriptionsService_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_prescriptionsService_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prescriptionsService_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
