// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prescriptions.proto

package server.services.prescriptionsService;

public interface PrescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prescriptionsService.Prescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string firstName = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 5;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 5;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string role = 6;</code>
   */
  java.lang.String getRole();
  /**
   * <code>string role = 6;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
