// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package server.services.authService;

public final class AuthServiceImpl {
  private AuthServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authService_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authService_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authService_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authService_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authService_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authService_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authService_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authService_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\013authService\"/\n\014LoginReques" +
      "t\022\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"e\n\017Re" +
      "gisterRequest\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010last" +
      "Name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010password\030\004 " +
      "\001(\t\022\014\n\004role\030\005 \001(\t\"f\n\004User\022\n\n\002id\030\001 \001(\t\022\021\n" +
      "\tfirstName\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\r\n\005em" +
      "ail\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\014\n\004role\030\006 \001(" +
      "\t\"%\n\rErrorResponse\022\024\n\014errorMessage\030\001 \001(\t" +
      "2~\n\004Auth\022=\n\010register\022\034.authService.Regis" +
      "terRequest\032\021.authService.User\"\000\0227\n\005login" +
      "\022\031.authService.LoginRequest\032\021.authServic" +
      "e.User\"\000B0\n\033server.services.authServiceB" +
      "\017AuthServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authService_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authService_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authService_LoginRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_authService_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authService_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authService_RegisterRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Password", "Role", });
    internal_static_authService_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_authService_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authService_User_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Password", "Role", });
    internal_static_authService_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_authService_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authService_ErrorResponse_descriptor,
        new java.lang.String[] { "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
