// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package server.services.authService;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authService.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 4;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string role = 5;</code>
   */
  java.lang.String getRole();
  /**
   * <code>string role = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
